
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/tjktest?characterEncoding=utf-8&serverTimezone=UTC
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver
 redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  database: 0
  lettuce:
   pool:
    max-idle: 16
    max-active: 32
    min-idle: 8
server:
 servlet:
  context-path: /demo
mybatis:
 # 下划线转驼峰
  map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml